[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

## should keep this commented out for now as it is not supported in the latest version of foundry and may cause issues such as modify variables silently when vm.roll() is called.
optimizer = true
optimizer_runs = 200
# via_ir = true